"""Reference trainer for the triage classifier.

Offline only. Trains a multinomial logistic regression with scikit-learn on the
feature columns of ``synthetic_dataset.csv`` and exports:

  * ``apps/api/src/classifier/model.json`` — coefficients, intercepts, and the
    standardisation parameters. Node performs inference as a dot product plus a
    softmax; there is no Python process at runtime.
  * ``metrics_report.md`` — accuracy, per-class precision/recall/F1, and the
    confusion matrix.

The dataset's feature columns are produced by ``apps/api/src/classifier/features.ts``
(via ``npm run ml:dataset``), so training and serving read the identical feature
vector and serving skew is structurally impossible.

Usage:
    python ml/train_triage_classifier.py
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

HERE = Path(__file__).resolve().parent
CSV = HERE / "synthetic_dataset.csv"
MODEL_OUT = HERE.parent / "apps" / "api" / "src" / "modules" / "classifier" / "model.json"
REPORT_OUT = HERE / "metrics_report.md"

TEST_FRACTION = 0.25
SEED = 20260820


def load() -> tuple[pd.DataFrame, list[str]]:
    if not CSV.exists():
        raise SystemExit(f"missing {CSV} — run `npm run ml:dataset` first")
    df = pd.read_csv(CSV)
    feature_names = [c for c in df.columns if c not in ("query", "label")]
    return df, feature_names


def render_report(
    accuracy: float,
    macro_f1: float,
    report: dict,
    cm: np.ndarray,
    labels: list[str],
    n_total: int,
    n_test: int,
) -> str:
    per_class_rows = "\n".join(
        "| `{label}` | {p:.3f} | {r:.3f} | {f:.3f} | {s} |".format(
            label=label,
            p=report[label]["precision"],
            r=report[label]["recall"],
            f=report[label]["f1-score"],
            s=int(report[label]["support"]),
        )
        for label in labels
    )

    cm_header = "| actual \\\\ predicted | " + " | ".join(f"`{l}`" for l in labels) + " |"
    cm_sep = "|---|" + "|".join("---" for _ in labels) + "|"
    cm_rows = "\n".join(
        "| `{label}` | {vals} |".format(label=labels[i], vals=" | ".join(str(int(v)) for v in row))
        for i, row in enumerate(cm)
    )

    # Describe the confusion the run actually produced rather than the one we
    # predicted. A report that asserts an expected error mode the matrix
    # contradicts is worse than no interpretation at all.
    worst_actual, worst_predicted, worst_count = None, None, 0
    for i, row in enumerate(cm):
        for j, count in enumerate(row):
            if i != j and count > worst_count:
                worst_actual, worst_predicted, worst_count = labels[i], labels[j], int(count)

    if worst_count == 0:
        confusion_note = (
            "This run produced no off-diagonal errors at all, which is itself a "
            "warning sign: the templates separate too cleanly to be a proxy for "
            "real operator language."
        )
    else:
        plural = "" if worst_count == 1 else "s"
        confusion_note = (
            f"The dominant error in this run is `{worst_actual}` misread as "
            f"`{worst_predicted}` ({worst_count} case{plural})."
        )
        if "simple_lookup" in (worst_actual, worst_predicted):
            confusion_note += (
                " That is the costly direction: `simple_lookup` is the class that "
                "changes routing, so an error here can send a lookup-shaped query "
                "down the vector path. It is bounded in practice because the hard "
                "router pins the path whenever a job ID or error code resolves "
                "against real data — the classifier only picks the RL state, never "
                "the path, when an anchor is present."
            )
        else:
            confusion_note += (
                " That is the cheap direction: both classes drive the same bandit "
                "exploration behaviour and differ only in the console's urgency "
                "badge, so the confusion costs a badge rather than a routing decision."
            )

    return f"""# Triage Classifier — Metrics Report

<!-- Generated by ml/train_triage_classifier.py. Do not edit by hand. -->

**Task:** 3-class triage of operator queries (`simple_lookup` / `complex_diagnostic` / `urgent_incident`)
**Model:** multinomial logistic regression (scikit-learn, lbfgs, L2)
**Trainer:** scikit-learn reference trainer
**Dataset:** {n_total} synthetic labelled queries, held-out split {int(TEST_FRACTION * 100)}% ({n_test} rows), seed {SEED}
**Generated:** {datetime.now(timezone.utc).isoformat()}

## Headline

| Metric | Value |
|---|---|
| Held-out accuracy | **{accuracy:.3f}** |
| Macro F1 | **{macro_f1:.3f}** |

## Per-class

| Class | Precision | Recall | F1 | Support |
|---|---|---|---|---|
{per_class_rows}

## Confusion matrix (held-out)

{cm_header}
{cm_sep}
{cm_rows}

## Honest interpretation

Accuracy on this dataset is high, and that number deserves its caveat: the
queries are generated from templates × entity slots, so the classifier is
learning the generator's vocabulary rather than real operator language. Treat it
as a working component with a reproducible evaluation, not as evidence about
production performance.

The confusion matrix is the informative part. {confusion_note}

The design anticipated `complex_diagnostic` ↔ `urgent_incident` as the main
error mode, on the reasoning that urgency and complexity co-occur in incident
language. Check the matrix above against that expectation on every retrain —
where they disagree, the matrix is the evidence and the expectation is the
hypothesis.

`simple_lookup` is separated largely by the structured-anchor features
(`has_job_id`, `has_error_code`), which are near-deterministic signals rather
than learned lexical cues. Those same anchors independently pin the retrieval
path upstream of the classifier, which is what bounds the blast radius of any
error in this class.
"""


def main() -> None:
    df, feature_names = load()

    X = df[feature_names].to_numpy(dtype=float)
    y_raw = df["label"].to_numpy()
    labels = sorted(set(y_raw.tolist()))
    y = np.array([labels.index(v) for v in y_raw])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_FRACTION, random_state=SEED, stratify=y
    )

    scaler = StandardScaler()
    X_train_z = scaler.fit_transform(X_train)
    X_test_z = scaler.transform(X_test)

    clf = LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        max_iter=2000,
        C=1.0,
        random_state=SEED,
    )
    clf.fit(X_train_z, y_train)

    y_pred = clf.predict(X_test_z)
    accuracy = accuracy_score(y_test, y_pred)
    macro_f1 = f1_score(y_test, y_pred, average="macro")
    report = classification_report(
        y_test, y_pred, target_names=labels, output_dict=True, zero_division=0
    )
    cm = confusion_matrix(y_test, y_pred, labels=list(range(len(labels))))

    # A constant column has zero variance; guard the divide rather than drop the
    # column, so the exported vector shape stays the compiled contract.
    stds = np.where(scaler.scale_ < 1e-9, 1.0, scaler.scale_)

    model = {
        "trained_by": "train_triage_classifier.py (scikit-learn)",
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "labels": labels,
        "feature_names": feature_names,
        "coefficients": np.round(clf.coef_, 6).tolist(),
        "intercepts": np.round(clf.intercept_, 6).tolist(),
        "means": np.round(scaler.mean_, 6).tolist(),
        "stds": np.round(stds, 6).tolist(),
    }

    MODEL_OUT.write_text(json.dumps(model, indent=2) + "\n", encoding="utf8")
    REPORT_OUT.write_text(
        render_report(accuracy, macro_f1, report, cm, labels, len(X), len(X_test)),
        encoding="utf8",
    )

    print(f"trained on {len(X_train)} rows, held-out accuracy {accuracy:.3f}")
    print(f"  model  -> {MODEL_OUT}")
    print(f"  report -> {REPORT_OUT}")


if __name__ == "__main__":
    main()
